### PR TITLE
Implement /dag/put route

### PR DESCRIPTION
**Pull request by matthiasbeyer**
I'm not sure where to look whether this is still experiemental, but anyways: I need it.

### CODE REVIEW

**Comment by sameer** [comment]
Looks like it's no longer experimental: http://127.0.0.1:8080/ipns/docs.ipfs.io/reference/api/http/#api-v0-dag-put

**Comment by ferristseng** [comment]
@matthiasbeyer Have you tested this? I think part of the reason it was commented was because I wasn't sure if it would work.

**Comment by matthiasbeyer** [comment]
I did not, no.

**Comment by ferristseng** [comment]
Ok, the docs are pretty light regarding how to use this route. I can try to find some time to test this.

**Pull request closed without merging**
