### PR TITLE
Pubsub message deserialization

### LINKED ISSUE #55: PubSub
Hello!

I tried to send and receive messages locally but sending "hello world" I received "aGVsbG8gd29ybGQ=".
If I use the CLI ipfs pubsub sub <topic> It work as expected which makes me thing there's a bug somewhere.

I'll look around and see if I can fix it.

Otherwise great API!

### PR DESCRIPTION
**Pull request by SionoiS**
Hello!

I'm trying to deserialize message correctly to fix #55. I haven't cracked the from field yet. Probably because PeerIds are now Ed25519 since go-ipfs 0.7.0

I'm not sure if having from, data and seqno as options is necessary. According to the [docs](https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-sub) those fields are not optional.

Also, where should I put the deserialize functions?

Thanks.

### CODE REVIEW

**Comment by SionoiS** [comment]
So PubSub message now deserialize to;

from -> base58btc peerid
,data -> Vec<u8>
,seqno -> usize
,all marked as optional.

I tried to get PeerId as Cid but it's too uncommon. Data as Vec<u8> allow arbitrary data to be received.

I will now try to send arbitrary data instead of utf8 text only.

**Comment by SionoiS** [comment]
Well nevermind..

Ideally ipfs should only i/o multibase encoded strings. For now the user will have to transcode. So I guess I'm done for now.

Let me know what you think!

**Comment by ferristseng** [comment]
Hi! Thanks for opening this. I'll try to get to it soon!

**Comment by SionoiS** [comment]
I just notice the failed test. Are empty messages even possible? I would think 'data' may be empty but 'from' and 'seqno' always present.

Maybe add a test for a message with an empty 'data' array.

**Pull request closed without merging**
